init:
- ps: >-
$webScriptRepository = "https://raw.githubusercontent.com/TFTomSun/Environment.GitHub/master/AppVeyor/"

function RunWebScript

{
 Param(
 [parameter(Mandatory=$true)][String]$scriptFileName,
 [parameter(ValueFromRemainingArguments=$true)][String[]]$arguments
    )

$url = $webScriptRepository + $scriptFileName;

$scriptFilePath = [io.path]::combine($($env:TEMP), $scriptFileName)

# Download the script

Invoke-WebRequest -Uri $url -OutFile $scriptFilePath

# Invoke the script

Invoke-Expression "$scriptFilePath $arguments"

}
environment:
  github_access_token:
    secure: pMOhRHsCASP9OJwLDjK+HLGcRbVO4msB9qVWaLP66kTWau5FVYvTuKWK33PyTNhE

version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
before_package:
- cmd: dotnet pack /p:Version=%APPVEYOR_BUILD_VERSION%
test_script:
- ps: RunWebScript "RunTests.ps1"   
artifacts:
- path: '**\*.nupkg'
  name: NugetPackages
deploy:
- provider: NuGet
  api_key:
    secure: 5Ct0G5LKjcTRtCJaabqaVaVgQCrQzNWjBiCbVQRj/gWRxooIw1MAoLxkyeUJi0yB
on_success:
  - ps: RunWebScript "UpdateReadme.ps1"